//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log4Core
    {
        public int Id { get; set; }
        public System.DateTime DateLog { get; set; }
        public string Thread { get; set; }
        public string MessageLog { get; set; }
        public string Exception { get; set; }
    }
}
