//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLSUsuario
    {
        public int IDUsuario { get; set; }
        public string Username { get; set; }
        public string Contraseña { get; set; }
        public string Email { get; set; }
        public long Cedula { get; set; }
        public string TipoCuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    }
}
